---
apiVersion: v1
kind: Service
metadata:
  name: payment
spec:
  type: LoadBalancer
  selector:
    app: payment
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: us-central1-docker.pkg.dev/GOOGLE_PROJECT/my-repository/payment:latest
          ports:
            - containerPort: 8080