spring.application.name=payment
spring.profiles.active=${PRODUCTION:dev}

# Database connection properties
spring.datasource.url=${JDBC_STAGING_DATABASE_URL:jdbc:postgresql://localhost:5432/be-payment}
spring.datasource.username=${JDBC_STAGING_DATABASE_USERNAME:postgres}
spring.datasource.password=${JDBC_STAGING_DATABASE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false

# Security
jwt.secret=${JWT_SECRET_KEY}
secret.salt=${SECRET_SALT}

# Midtrans Configuration
midtrans.production=${MIDTRANS_IS_PRODUCTION}


## Actuator
management.endpoints.web.exposure.include=*
management.endpoint.prometheus.access=read_only
management.endpoint.health.show-details=always