spring.application.name=payment
spring.profiles.active=${PRODUCTION:dev}

# Midtrans Configuration
midtrans.server.key=YOUR_SANDBOX_SERVER_KEY
midtrans.client.key=YOUR_SANDBOX_CLIENT_KEY
midtrans.api.url=https://app.sandbox.midtrans.com/snap/v1/transactions
midtrans.subscription.api.url=https://api.sandbox.midtrans.com/v1/subscriptions
midtrans.gopay.callback.url=YOUR_GOPAY_CALLBACK_URL # Replace with your actual callback URL
midtrans.get.pay.account.api.url=https://api.sandbox.midtrans.com/v2/pay/account/



## Actuator
management.endpoints.web.exposure.include=*
management.endpoint.prometheus.access=read_only
management.endpoint.health.show-details=always